### ISSUE TITLE
Unusual behaviour regarding change direction of train.

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/ROSTimetableEditor#19] opened 2020-02-28 20:25 UTC
Please see the section of a generated timetable:

`07:00 1A01;Bidston to James Street;60;120;107;35;656,07:00;Snt;5-13 6-13,07:01;07:02;Conway Park,07:04;07:04;Hamilton Square,07:06;James Street,07:06;Fns;1B01`

In the program itself, I added a change of direction at James Street at 07:07:

![image](https://user-images.githubusercontent.com/56364196/75584518-cfa43d00-5a67-11ea-970e-613ce4104e88.png)

My personal preference is to have a change direction before forming a new service. Could the program detect this change direction flag, and change the time of finish and form new service?

This is similar to another issue, but the fix is not yet in the latest Windows release, possibly related? https://github.com/Railway-Op-Sim/ROSTimetableEditor/issues/15

Thanks,
Daniel

**Comment by zarethrex** [comment] 2020-02-29 11:04
Yes this is a known issue and has been resolved, just not in latest build.
Duplicate of https://github.com/Railway-Op-Sim/ROSTimetableEditor/issues/15.

**Closed as completed by zarethrex** 2020-02-29 11:04 UTC
